### ISSUE TITLE
Thank you for the revamp of docker-cli

### ISSUE THREAD

**Issue by StefanScherer** [geicht/chocolatey-packages#1]
Hey @geicht 
I want to thank you for the great revamp of the docker-cli package. Somehow I didn't get your request to be added as a maintainer. 
But from what I can see, you improved the whole process a lot, use a GitHub action, use AU packages, use the upstream binaries. 💯 🎉 
Thanks,
Stefan

**Comment by geicht** [comment]
Hello @StefanScherer ,
I'm glad I could help. Everyone can now enjoy an up-to-date docker-cli package 😄.
If you don't mind I would continue maintaning it for the foreseeable future.
Regards,
Geicht

**Comment by StefanScherer** [comment]
Yes I‘m fine with this. Thanks for taking action.
