### ISSUE TITLE
miniforge3 not added to PATH with `--params="'/AddToPath:1'"`

### ISSUE THREAD

**Issue by Vinfall** [geicht/chocolatey-packages#4]
Install miniforge3 with the following param on Windows 11 Canary, and conda/mamba commands are still unavailable after `refreshenv`. I noticed that by default miniforge3 would add PATH via registry (see https://github.com/conda-forge/miniforge/issues/520) instead of appending environment variables. I do have `Computer\HKEY_CURRENT_USER\Software\Microsoft\Command Processor`, but `AutoRun` key is missing, not sure if it's related.

```powershell
refreshenv

choco install miniforge3 --params="'/AddToPath:1'"
```

**Comment by geicht** [comment]
It seems that upstream conda distributions removed support for the `AddToPath` parameter when used in an all user installation, for security reasons (more information and workarounds at https://github.com/ContinuumIO/anaconda-issues/issues/12995#issuecomment-1188441961). I will update the chocolatey packages to reflect that change.
